name: 'Atlas CLI GitHub Action'
description: 'Use AtlasCLI in your GitHub workflow'
branding:
  icon: 'terminal'
  color: 'green'
inputs:
  version:
    description: 'AtlasCLI version to use in your workflow'
    required: false
    default: 'latest'
runs:
  using: 'docker'
  image: docker://nicohrubec266/atlascli:${{ env.INPUT_VERSION }}
  entrypoint: 'atlas'
