name: 'Atlas CLI GitHub Action'
description: 'Use AtlasCLI in your GitHub workflow'
branding:
  icon: 'terminal'
  color: 'green'
inputs:
  version:
    description: Version of the Atlas CLI to install
    required: false
    default: 'latest'
runs:
  using: 'composite'
  steps:
    - name: Find latest tag
      if: ${{ github.event.inputs.version }} == 'latest'
      uses: oprypin/find-latest-tag@v1
      id: find-latest-tag
      with:
        repository: mongodb/mongodb-atlas-cli
        releases-only: true
        regex: 'atlascli*'
    - name: Determine tag
      shell: bash
      run: |
        if ${{ github.event.inputs.version }} == 'latest'
        then
          echo "use latest tag"
        else
          echo "use input tag"
        fi

    - name: Download release
      uses: robinraju/release-downloader@v1.8
      id: download-release
      with:
        repository: mongodb/mongodb-atlas-cli
        tag: ${{ steps.find-latest-tag.outputs.tag }}
        fileName: 'mongodb-atlas-cli*linux_x86_64.deb'
    - name: Print latest tag
      shell: bash
      run: echo "CLI is at version ${{ steps.find-latest-tag.outputs.tag }}"
