name: 'Atlas CLI GitHub Action'
description: 'Use AtlasCLI in your GitHub workflow'
branding:
  icon: 'terminal'
  color: 'green'
runs:
  using: 'composite'
  steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        repository: mongodb/mongodb-atlas-cli
        fetch-depth: 0
    - uses: oprypin/find-latest-tag@v1
      id: get-latest-tag
      with:
        repository: mongodb/mongodb-atlas-cli
        releases-only: true
        regex: 'atlascli*'
    - name: Print latest tag
      shell: bash
      run: echo "CLI is at version ${{ steps.get-latest-tag.outputs.tag }}"
