name: 'Atlas CLI GitHub Action'
description: 'Use AtlasCLI in your GitHub workflow'
branding:
  icon: 'terminal'
  color: 'green'
runs:
  using: 'composite'
  steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        repository: mongodb/mongodb-atlas-cli
        fetch-depth: 0
    - name: 'Get latest tag'
      shell: bash
      run: echo "tag=$(git tag --list --sort=-version:refname "atlascli*" | head -n 1)" >> $GITHUB_OUTPUT
    - name: 'Echo version'
      shell: bash
      run: echo "${{ steps.get-latest-tag.outputs.tag }}"
