name: 'Atlas CLI GitHub Action'
description: 'Use AtlasCLI in your GitHub workflow'
branding:
  icon: 'terminal'
  color: 'green'
runs:
  using: 'composite'
  steps:
    - uses: oprypin/find-latest-tag@v1
      id: get-latest-tag
      with:
        repository: mongodb/mongodb-atlas-cli
        releases-only: true
        regex: 'atlascli*'
    - uses: robinraju/release-downloader@v1.8
      id: download-release
      with:
        repository: mongodb/mongodb-atlas-cli
        tag: ${{ steps.get-latest-tag.outputs.tag }}
        fileName: 'mongodb-atlas-cli*linux_x86_64.deb'
    - name: Print latest tag
      shell: bash
      run: echo "CLI is at version ${{ steps.get-latest-tag.outputs.tag }}"
    - name: Install atlas
      shell: bash
      run: |
        chmod +x /home/runner/work/atlas-github-action/atlas-github-action/mongodb-atlas-cli_1.10.0_linux_x86_64.deb
        cd /home/runner/work/atlas-github-action/atlas-github-action
        ls .
        ./mongodb-atlas-cli_1.10.0_linux_x86_64.deb
