name: 'Atlas CLI GitHub Action'
description: 'Use AtlasCLI in your GitHub workflow'
branding:
  icon: 'terminal'
  color: 'green'
runs:
  using: 'docker'
  image: 'docker://nicohrubec266/atlascli:latest'
  entrypoint: '/entrypoint.sh'
  env:
    MONGODB_ATLAS_PUBLIC_API_KEY: ${{ inputs.public_api_key }}
    MONGODB_ATLAS_PRIVATE_API_KEY: ${{ inputs.private_api_key }}
  args:
    - ${{ inputs.arg1 }}
    - ${{ inputs.arg2 }}
