name: Test AtlasCLI action
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Use AtlasCLI
    runs-on: ubuntu-latest
    steps:
      - name: AtlasCLI
        id: cli
        uses: nicohrubec/atlas-github-action@main
        env:
          MONGODB_ATLAS_PUBLIC_API_KEY: ${{ inputs.public_api_key }}
          MONGODB_ATLAS_PRIVATE_API_KEY: ${{ inputs.private_api_key }}
          MONGODB_ATLAS_ORG_ID: ${{ inputs.org_id }}
          MONGODB_ATLAS_PROJECT_ID: ${{ inputs.project_id }}
        with:
          arg1: projects
          arg2: create
          arg3: test-project
      - name: Get the project id
        run: echo "The id of the created project is ${{ steps.cli.outputs.projectId }}"
