name: Test AtlasCLI action
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Print goodbye
    runs-on: ubuntu-latest
    steps:
      - name: AtlasCLI
        uses: https://github.com/nicohrubec/atlas-github-action@main
