name: Test AtlasCLI action
on:
  push:
jobs:
  test:
    name: Use AtlasCLI
    runs-on: ubuntu-latest
    env:
      MONGODB_ATLAS_PUBLIC_API_KEY: ${{ secrets.PUBLIC_API_KEY }}
      MONGODB_ATLAS_PRIVATE_API_KEY: ${{ secrets.PRIVATE_API_KEY }}
      MONGODB_ATLAS_ORG_ID: ${{ secrets.ORG_ID }}
      MONGODB_ATLAS_PROJECT_ID: ${{ secrets.PROJECT_ID }}
    steps:
      - name: AtlasCLI
        id: cli
        uses: nicohrubec/atlas-github-action@main
        with:
          args: projects create test-project
      - name: AtlasCLI-projects-list
        id: cli-projects-list
        uses: nicohrubec/atlas-github-action@main
        with:
          args: projects list
