name: Test AtlasCLI Action
on:
  push:
jobs:
  env:
    - MONGODB_ATLAS_PUBLIC_API_KEY: ${{ secrets.PUBLIC_API_KEY }}
    - MONGODB_ATLAS_PRIVATE_API_KEY: ${{ secrets.PRIVATE_API_KEY }}
    - MONGODB_ATLAS_ORG_ID: ${{ secrets.ORG_ID }}
    - MONGODB_ATLAS_PROJECT_ID: ${{ secrets.PROJECT_ID }}
  no-version:
    name: Use AtlasCLI without version input
    runs-on: ubuntu-latest
    steps:
      - name: Setup AtlasCLI without version input
        uses: mongodb/atlas-github-action@main
      - name: Use AtlasCLI
        shell: bash
        run: atlas --help
  input-version:
    name: Use AtlasCLI with version input
    runs-on: ubuntu-latest
    steps:
      - name: Setup AtlasCLI with version input
        uses: mongodb/atlas-github-action@main
        with:
          version: v1.9.0
      - name: Use AtlasCLI
        shell: bash
        run: atlas --help
