name: Test AtlasCLI action
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Use AtlasCLI
    runs-on: ubuntu-latest
    steps:
      - name: AtlasCLI
        uses: nicohrubec/atlas-github-action@main
        with:
          public_api_key: ${{ secrets.PUBLIC_API_KEY }}
          private_api_key: ${{ secrets.PRIVATE_API_KEY }}
          arg1: clusters
          arg2: list
