name: Test AtlasCLI action
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Use AtlasCLI
    runs-on: ubuntu-latest
    steps:
      - name: AtlasCLI
        id: cli
        uses: nicohrubec/atlas-github-action@main
        with:
          public_api_key: ${{ secrets.PUBLIC_API_KEY }}
          private_api_key: ${{ secrets.PRIVATE_API_KEY }}
          org_id: ${{ secrets.ORG_ID }}
          project_id: ${{ secrets.PROJECT_ID }}
          arg1: projects
          arg2: create
          arg3: test-project
      - name: Get the project id
        run: echo "The id of the created project is ${{ steps.cli.outputs.projectId }}"
